name: saltstack-sysvinit-formula
source: https://github.com/bechtoldt/saltstack-sysvinit-formula
summary: SaltStack Formula to set up and configure sysvinit, an init system
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
